config/urls.py
from index import views
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', include('index.urls')),
    path('', views.index, name='index'),
    path('psbo/', include('psbo.urls')),
    path('common/', include('common.urls')),
]

index/urls.py
from django.urls import path
from . import views

app_name = 'index'

urlpatterns = [
    path('', views.index, name='index'),
    path('introduce/', views.introduce, name='introduce'),
    path('room/', views.room, name='room'),
    path('travel/', views.travel, name='travel'),
    path('fac/', views.fac, name='fac'),
    path('reservation/', views.reservation, name='reservation'),
    path('location', views.location, name='location'),
    path('reservating/', views.reservating, name='reservating'),
    path('reservating2/', views.reservating2, name='reservating2'),
    path('reserve/', views.reserve, name='reserve'),
    path('charge_info/', views.charge_info, name='charge_info'),

    path('room/101/', views.room101, name='room101'),
    path('room/201/', views.room201, name='room201'),
    path('room/301/', views.room301, name='room301'),


    path('popup/', views.popup, name='popup'),
    path('test/', views.test, name='test'),

]

psbo/urls.py
from django.urls import path
from . import views


app_name = 'psbo'


urlpatterns = [
    path('', views.board, name='board'),
    path('<int:question_id>/', views.detail, name='detail'),


    path('question/create/', views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', views.question_delete, name="question_delete"),


    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', views.answer_delete, name='answer_delete'),
]

templates/index/fac_info.html
{% extends 'base.html' %}
{% load static%}
<!-- CSS 스타트 -->
{% block style %}
<!-- CSS는 따로 빼지 마시고 이쪽에 따로 작성하셔도 됩니다. -->

{% endblock %}
<!-- CSS 끝 -->
<!-- 본문내용 스타트 -->
{% block content %}
<br>
<div class="container my-1">
        <div class="card">
            <div id ="carouselCon" class="carousel slide w-auto mx-auto" data-ride="carousel">
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <img src="{% static 'img_main/1.jpg' %}" class="d-block w-100" alt="...">
                    </div>
                    <div class="carousel-item">
                        <img src="{% static 'img_main/2.jpg' %}" class="d-block w-100" alt="...">
                    </div>
                    <div class="carousel-item">
                        <img src="{% static 'img_main/3.jpg' %}" class="d-block w-100" alt="...">
                    </div>
                    <div class="carousel-item">
                        <img src="{% static 'img_main/4.jpg' %}" class="d-block w-100" alt="...">
                    </div>
                </div>
                <a class="carousel-control-prev " href="#carouselCon" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next " href="#carouselCon" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>  <!-- 메인 화면 사진 -->
          </div>
        </div>
</div>
<div class="container my-1">
    <!-- 상단 테이블 시작-->
    <div class="text-center">
        <h2 class="my-5"><i class="fas fa-map-pin fa-lg"></i> 주변 편의시설 소개</h2>
    </div>
    <!--상단 테이블 끝-->
    <div class="container-fluid">
        <!-- 카드 시작-->
        <div class="card">
            <div class="card-body">
                <img src="{% static 'fac/fac!!.png' %}"
                   style="max-width: 100%; height: auto; display: block; border-radius: 10px;" alt="메인뷰"><br>
                <h1 style="text-align:center"><strong>펜션 주변 편의 시설을 이용해보세요!!</strong></h1>
                <div class="row">
                    <div class="col-4" style="margin-bottom:10px">
                        <a href="#fac1" style="text-decoration-line:none"><button type="button" class="btn btn-outline-dark btn-block">하나로 마트</button></a>
                    </div>
                    <div class="col-4" style="margin-bottom:10px">
                        <a href="#fac2" style="text-decoration-line:none"><button type="button" class="btn btn-outline-dark btn-block">이마트(emart)</button></a>
                    </div>
                    <div class="col-4" style="margin-bottom:10px">
                        <a href="#fac3" style="text-decoration-line:none"><button type="button" class="btn btn-outline-dark btn-block">주유소</button></a>
                    </div>
                    <div class="col-4">
                        <a href="#fac4" style="text-decoration-line:none"><button type="button" class="btn btn-outline-dark btn-block">편의점</button></a>
                    </div>
                    <div class="col-4">
                        <a href="#fac5" style="text-decoration-line:none"><button type="button" class="btn btn-outline-dark btn-block">배달음식</button></a>
                    </div>
                    <div class="col-4">
                        <a href="#fac6" style="text-decoration-line:none"><button type="button" class="btn btn-outline-dark btn-block">공원 및 산책로</button></a>
                    </div>
                </div>
            </div>
        </div>
        <!-- 카드 끝-->
<br>
        <!-- 전체 편의시설 목록 시작-->
        <!-- 첫 행 시작-->
        <div class="container">
            <div class="row">
                <div class="col-6" id="fac1">
                    <div class="card">
                        <div class="card-header">
                            <img src="{% static 'fac/nhmart.jpg' %}"
                             style="max-width: 100%; height: auto; display: block; border-radius: 10px;" alt="하나로 마트">
                        </div>
                        <div class="card-body">
                            <h4 class="card-title">하나로 마트(○○점)</h4>
                            <div class="card-text">
                                <p>위치 : <a href="https://map.naver.com/v5/entry/place/37244081?c=14312419.9902730,4606954.4300789,15,0,0,0,dh" target="_blank">강원 속초시 동해대로 4202</a></p>
                                <p>전화번호 : 033-630-○○○○</p>
                                <p>영업시간 : 평일 08:30 ~ 19:00</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-6" id="fac2">
                    <div class="card">
                        <div class="card-header">
                            <img src="{% static 'fac/emart.jpg' %}"
                             style="max-width: 100%; height: auto; display: block; border-radius: 10px;" alt="이마트">
                        </div>
                        <div class="card-body">
                            <h4 class="card-title">이마트(emart)</h4>
                            <div class="card-text">
                                <p>위치 : <a href="https://map.naver.com/v5/entry/place/11605018?c=14255578.6107454,4606458.5351352,8,0,0,0,dh" target="_blank">강원 속초시 설악금강대교로 12</a></p>
                                <p>전화번호 : 033-780-○○○○</p>
                                <p>영업시간 : 매일 10:00 ~ 23:00</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--첫 행 끝-->
<br>
        <!-- 2 행 시작-->
        <div class="container">
            <div class="row">
                <div class="col-6" id="fac3">
                    <div class="card">
                        <div class="card-header">
                            <img src="{% static 'fac/skoil.jpg' %}"
                             style="max-width: 100%; height: auto; display: block; border-radius: 10px;" alt="주유소">
                        </div>
                        <div class="card-body">
                            <h4 class="card-title">주유소</h4>
                            <p class="card-text">
                                <p>위치 : <a href="https://map.naver.com/v5/entry/place/19801655?c=14309725.5687900,4606514.1133886,13,0,0,0,dh" target="_blank">강원 속초시 동해대로 4168</a></p>
                                <p>전화번호 : 033-999-○○○○</p>
                                <p>영업시간 : 매일 00:00 ~ 00:00 (24시운영)</p>
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-6" id="fac4">
                    <div class="card">
                        <div class="card-header">
                            <img src="{% static 'fac/gs25.jpg' %}"
                             style="max-width: 100%; height: auto; display: block; border-radius: 10px;" alt="편의점">
                        </div>
                        <div class="card-body">
                            <h4 class="card-title">편의점</h4>
                            <p class="card-text">
                                <p>위치 : <a href="https://map.naver.com/v5/entry/place/32506508?c=14285037.4549484,4608971.8100817,10,0,0,0,dh" target="_blank">강원 속초시 중앙로 205</a></p>
                                <p>전화번호 : 033-8888-○○○○</p>
                                <p>영업시간 : 매일 00:00 ~ 00:00 (24시 운영)</p>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--2 행 끝-->
<br>
        <!-- 3 행 시작-->
        <div class="container">
            <div class="row">
                <div class="col-6" id="fac5">
                    <div class="card">
                        <div class="card-header">
                            <img src="{% static 'fac/ride.png' %}"
                             style="max-width: 100%; height: auto; display: block; border-radius: 10px;" alt="배달의 민족, 요기요 로고">
                        </div>
                        <div class="card-body">
                            <h4 class="card-title">배달</h4>
                            <p class="card-text">
                                <p>위치 : 강원 oo군 oo면 oo로 0000길 00-00</p>
                                <p>전화번호 : 033-○○○-○○○○</p>
                                <p>영업시간 : 매장별로 상이함 </p>
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-6" id="fac6">
                    <div class="card">
                        <div class="card-header">
                            <img src="{% static 'fac/park.PNG' %}"
                             style="max-width: 100%; height: auto; display: block; border-radius: 10px;" alt="공원 및 산책로">
                        </div>
                        <div class="card-body">
                            <h4 class="card-title">공원 및 산책로</h4>
                            <p class="card-text">
                                <p>위치 : <a href="https://map.naver.com/v5/entry/place/1666471524?c=14315793.0153718,4605304.3909188,15,0,0,0,dh">강원 속초시 대포동 656-14</a></p>
                                <p>전화번호 : 033-980-○○○○</p>
                                <p>영업시간 : 매일 06:00 ~ 20:00</p>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--3 행 끝-->
        <!-- 전체 편의시설 목록 끝-->
    </div>
</div>
<!-- 위의 내용은 일단은 기본형식으로 하고 아래부터 HTML 코드로 작성하시면 됩니다. -->

{% endblock %}
<!-- 본문내용 끝 -->

templates/index/index.html
{% extends 'base.html' %}
{% load static %}
<!-- CSS 스타트 -->
{% block style %}
<!-- CSS는 따로 빼지 마시고 이쪽에 따로 작성하셔도 됩니다. -->
{% endblock %}
<!-- CSS 끝 -->
<!-- 본문내용 스타트 -->
{% block content %}
<br>
    <div class="container my-1">
    <!-- 카드 스타일-->
        <div class="card" id="main">

          <div class="card-body" style="text-align: center;">
            <img src="{% static 'pension_main.jpg' %}"
                 style="max-width: 100%; height: auto; display: block; border-radius: 10px;" alt="main">
          </div>

          <div class="container">
              <div class="h6 border-bottom py-1 font-weight-bolder">
                  <i class="fas fa-flag-checkered"></i>&nbsp;&nbsp;안내사항 (Pension Notice)
              </div>
          </div>

          <div class="row">

                <div class="col-4">
                  <div class="card-body">
                    <img src="{% static 'main_banner2.jpg' %}"
                         style="max-width: 100%; height: auto; display: block; border-radius: 10px;" alt="main">
                    <div class="card-body">
                        <h5 class="card-title"><strong>현재는 성수기 요금입니다</strong></h5>
                      <p class="card-text">성수기<br>2021년 07월 17일~2021년 08월 07일</p>
                    </div>
                  </div>
                </div>

                <div class="col-4">
                  <div class="card-body">
                    <img src="{% static 'main_banner1.jpg' %}"
                         style="max-width: 100%; height: auto; display: block; border-radius: 10px;" alt="main">
                    <div class="card-body">
                        <h5 class="card-title"><strong>야외수영장 개장중</strong></h5>
                      <p class="card-text">개장 일자/시간<br>
                          2021년 06월 15일~2021년 09월 30일<br>오전 11:00 ~ 오후 09:00</p>
                    </div>
                  </div>
                </div>

                <div class="col-4">
                  <div class="card-body">
                    <img src="{% static 'main_banner3.jpg' %}"
                         style="max-width: 100%; height: auto; display: block; border-radius: 10px;" alt="main">
                    <div class="card-body">
                        <h5 class="card-title"><strong>방영지침에 의한 소독</strong></h5>
                      <p class="card-text">손님들의 안전을 위해<br>매일 1회 소독을 실시하고 있습니다.<br>
                            소독타임(오전11시~오후1시)에는<br>자리이동등의 협조 부탁드립니다.</p>
                    </div>
                  </div>
                </div>

          </div>

          <div class="container">
              <div class="h6 border-bottom py-1 font-weight-bolder">
                  &nbsp;&nbsp;'코로나19' 관련 안내사항
              </div>
          </div>
              <ul class="slide my-1">
                    <li style="list-style:none;"><i class="fas fa-hand-point-up"></i>
                        &nbsp;예정되어 있는 횡성한우축제는 정부방역지침에 따라 연기되었습니다.
                    </li>
                    <li style="list-style:none;"><i class="fas fa-hand-point-up"></i>
                        &nbsp;코로나 단계 상승으로 인하여 주변 대형마트들은 오후 09시까지 단축운영합니다.
                    </li>
                    <li style="list-style:none;"><i class="fas fa-hand-point-up"></i>
                        &nbsp;펜션내에서도 가급적 마스크착용을 부탁드리며, 타 고객과의 접촉을 최대한 자제하시길 부탁드립니다.
                    </li>
                    <li style="list-style:none;"><i class="fas fa-hand-point-up"></i>
                        &nbsp;관리동에 용무가 있으신분들은 먼저 연락을 주시기바랍니다. 비대면으로 해결가능한일은 펜션지기가 최대한 빠르게 비대면으로 해결해 드리겠습니다.
                    </li>
              </ul>
          </div>
        </div>
    </div>

{% endblock %}
<!-- 본문내용 끝 -->

<!--자바스크립트 Start-->
{% block script %}

<script>
$(document).ready(function() {

//슬라이드
    $('.slide').inewsticker({
        speed       : 3500,
        effect      : 'slide',
        dir         : 'ltr',
        font_size   : 15,
        color       : '#000',
        font_family : 'arial',
        delay_after : 1000
    });

});
</script>
<script src="{% static 'inewsticker/inewsticker.js' %}"></script>
<script src="https://use.fontawesome.com/releases/v5.2.0/js/all.js"></script>
<script>
    window.open("{% url 'index:popup' %}", "popup", "width=400, height=600, left=10, top=170")
</script>
{% endblock %}
<!--자바스크립트 End-->

templates/index/popuppage.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>코로나 집합금지</title>
</head>
<body>
      <img src="{% static 'popup.jpg' %}" alt="popuppage">
</body>
</html>

templates/index/reservating.html
{% extends 'base.html' %}
{% load static %}
<!-- CSS 스타트 -->
{% block style %}
<!-- CSS는 따로 빼지 마시고 이쪽에 따로 작성하셔도 됩니다. -->

{% endblock %}
<!-- CSS 끝 -->
<!-- 본문내용 스타트 -->
{% block content %}
<br>
<div class="container my-1">

<br>
    <div class="card">
      <div class="card-body" style="text-align: center;">
          <strong>본 사이트는 과제를 위한 포트폴리오 사이트입니다.<br>
              해당링크는 실제하는 링크이므로 확인만하시고 실제로 예약을 하진 마십시오.</strong>
      </div>
    </div>
<br>
    <div class="container-fluid">
<br>
        <div class="card">
          <div class="card-body" style="text-align: center;">
             <div id="mwb-page" class="container page">
                <div class="mwb-card mwb-shadow-none mwb-bg-transparent">
                    <div class="body">
                        <h1>
                            <i class="far fa-calendar-alt"></i> 실시간 예약
                        </h1>
                    </div>
                </div>
                    <div class="mwb-card mwb-information-cal mwb-mb-50">
                    <div class="body">
                            <script>
                                callYapenCalendar('reserveCalendar','57385','Y','');
                            </script>
                            <div class="reservation-cal-sm visible-lg visible-md visible-sm">
                                <!-- <div id="reserveCalendar"></div> -->
                                <iframe src="https://www.yapen.co.kr/external?ypIdx=57385" frameborder='0' width='100%' height='1200' scrolling='auto'></iframe>
                            </div>
                            <div class="reservation-cal-xs visible-xs">
                                <a href="https://www.yapen.co.kr/external?ypIdx=57385" class="btn btn-lg btn-success btn-block" target="_self">예약하기</a>
                            </div>
                    </div>
                </div>
             </div>
          </div>
        </div>

    </div>
</div>
<br>

<!-- 위의 내용은 일단은 기본형식으로 하고 아래부터 HTML 코드로 작성하시면 됩니다. -->

{% endblock %}
<!-- 본문내용 끝 -->


{% block script %}
    <script src="https://use.fontawesome.com/relases/v5.2.0/js/all.js"></script>
{% endblock%}

templates/index/reservating2.html
{% extends 'base.html' %}
{% load static %}
<!-- CSS 스타트 -->
{% block style %}
    .table tr td{ border:1px solid #ccc;}
    .table tr td:nth-of-type(1){ color:red }
    .table tr td:nth-of-type(7){ color:blue }
    .dates tr td{ height:2rem; font-size:0.85rem; height:240px; width:135px}
    #today { background-color:rgba(255,0,0,0.1) ; border:2px solid red  }
    .circle {width:10px ;height:10px ; border-radius:50%; margin: 5px ; font-size: 0.5rem;}
    .reservate { background-color: green }
    .rewait { background-color: orange }
    .recomplet { background-color: gray }
    .salewait { background-color: cornflowerblue }
<!-- CSS는 따로 빼지 마시고 이쪽에 따로 작성하셔도 됩니다. -->
{% endblock %}
<!-- CSS 끝 -->
<!-- 본문내용 스타트 -->
{% block content %}
<br>
<div class="container my-1">
  <div class="card">
    <div class="container my-4">
        <div class="d-flex justify-content-between border-bottom">
            <div>
                <strong>Pension Paradise 실시간예약안내</strong>
            </div>
            <div>
                <ul class="nav list-unstyled">
                    <li class="nav-item"><a class="nav-link" href="{% url 'index:reservating2' %}">예약달력</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'index:reserve' %}">예약하기</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'index:charge_info' %}">요금안내</a></li>
                </ul>
            </div>
        </div>
        <div class="my-3 d-flex justify-content-between">
                <div class="d-flex align-text-top pt-2" style="font-size:0.75rem">
                    <div class="circle reservate"></div>예약하기 <div class="circle rewait"></div>입금대기
                    <div class="circle recomplet"></div>예약완료 <div class="circle salewait"></div>판매대기
                </div>
                <div class="YearMonth mr-3">
                    <button class="prebtn"><i class="fas fa-caret-left"></i></button>
                    <label class="YM"></label>
                    <button class="nextbtn"><i class="fas fa-caret-right"></i></button>
                </div>
                <div>
                    <button class="Now">오늘</button>
                </div>
        </div>
        <table class="table my-3">
            <thead>
                <tr class="font-weight-bold">
                    <td>일요일</td>
                    <td>월요일</td>
                    <td>화요일</td>
                    <td>수요일</td>
                    <td>목요일</td>
                    <td>금요일</td>
                    <td>토요일</td>
                </tr>
            </thead>
            <tbody class="dates">
            </tbody>
        </table>
    </div>
  </div>
</div>
<form method="get" action="{% url 'index:reserve' %}" id="time">
    <input type="hidden" id="year" name="year" value="{{year|default_if_none:'' }}">
    <input type="hidden" id="month" name="month" value="{{month|default_if_none:'' }}">
    <input type="hidden" id="date" name="date" value="{{date|default_if_none:'' }}">
    <input type="hidden" id="roomN" name="roomN" value="{{roomN|default_if_none:'' }}">
</form>
{% endblock %}
<!-- 본문내용 끝 -->
{% block script %}
    <script src="https://use.fontawesome.com/releases/v5.2.0/js/all.js"></script>
    <script>
        var Nowdate = new Date();
        function renderCalender(date){
            var Year = date.getFullYear();
            var Month = date.getMonth();

            var startdate = new Date(Year,Month,1)
            var lastdate = new Date(Year,Month+1,0)

            var tag="<tr>";
            var cnt = 0;
            for(i=0;i<startdate.getDay();i++){
                tag+="<td></td>";
                cnt++;
            }

            date_value= "<div style='color:black'>" +
                    "<div class='d-flex my-1'><div class='circle reservate'></div><a href='#'>101호</a></div>" +
                    "<div class='d-flex my-1'><div class='circle reservate'></div><a href='#'>102호(독채)</a></div>" +
                   "<div class='d-flex my-1'><div class='circle reservate'></div><a href='#'>201호(스파)</a></div>" +
                    "<div class='d-flex my-1'><div class='circle reservate'></div><a href='#'>202호(스파)</a></div>" +
                   "<div class='d-flex my-1'><div class='circle reservate'></div><a href='#'>301호(스파)</a></div>" +
                    "<div class='d-flex my-1'><div class='circle reservate'></div><a href='#'>302호(스파)</a></div>" +
                    "<div class='d-flex my-1'><div class='circle reservate'></div><a href='#'>303호(스파)</a></div>" +
                    "<div class='d-flex my-1'><div class='circle reservate'></div><a href='#'>304호(스파)</a></div> </div>"

            for(i = 1; i<=lastdate.getDate();i++){
                if(cnt % 7 == 0) tag += "<tr>";
                if(i == Nowdate.getDate() && date.getMonth() == Nowdate.getMonth())
                    tag += "<td id='today' data-date="+i+">" + i+date_value + "</td>";
                else if(date.getMonth() > Nowdate.getMonth() || i > Nowdate.getDate())
                    tag += "<td data-date="+i+">" + i + date_value + "</td>";
                else
                    tag += "<td>"+i+"</td>"
                cnt++;
                if(cnt % 7 == 0)
                    tag  += "</tr>";
            }

            $('.dates').html(tag);
            $('.YM').html(Year + "년" +(Month+1) + "월");
            if(Month == Nowdate.getMonth())
                $('.prebtn').attr("disabled",true);
            else
            {
                $('.prebtn').attr("disabled",false);
            }
            if(Month == Nowdate.getMonth()+3)
                $('.nextbtn').attr("disabled",true);
            else
            {
                $('.nextbtn').attr("disabled",false);
            }
        }
        var pdate = Nowdate
        renderCalender(pdate)

        function ClickUpdate()
        {
            $('.dates a').on('click',function(){
                console.log("D")
                $('#date').val($(this).closest('td').data("date"))
                $('#month').val(pdate.getMonth())
                $('#year').val(pdate.getFullYear())
                $('#roomN').val(($(this).text().substring(0,3)))
                $('#time').submit();
            })
        }

        $(function(){
            $('.nextbtn').on('click',function(){
                pdate = new Date(pdate.getFullYear(),pdate.getMonth()+1,1)
                renderCalender(pdate);
                ClickUpdate()

            });
            $('.prebtn').on('click',function(){
                pdate = new Date(pdate.getFullYear(),pdate.getMonth(),0)
                renderCalender(pdate);
                ClickUpdate()
            });
            $('.Now').on('click',function(){
                renderCalender(Nowdate);
                pdate=Nowdate;
                ClickUpdate()
            })
            ClickUpdate()
        });
    </script>
{% endblock %}

templates/index/room_info.html
{% extends 'base.html' %}
{% load static %}
<!-- CSS 스타트 -->
{% block style %}
<!-- CSS는 따로 빼지 마시고 이쪽에 따로 작성하셔도 됩니다. -->

{% endblock %}
<!-- CSS 끝 -->
<!-- 본문내용 스타트 -->
{% block content %}
<br>
<div class="container my-1">
        <div class="card">
            <div id ="carouselCon" class="carousel slide w-auto mx-auto" data-ride="carousel">
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <img src="{% static 'img_main/1.jpg' %}" class="d-block w-100" alt="...">
                    </div>
                    <div class="carousel-item">
                        <img src="{% static 'img_main/2.jpg' %}" class="d-block w-100" alt="...">
                    </div>
                    <div class="carousel-item">
                        <img src="{% static 'img_main/3.jpg' %}" class="d-block w-100" alt="...">
                    </div>
                    <div class="carousel-item">
                        <img src="{% static 'img_main/4.jpg' %}" class="d-block w-100" alt="...">
                    </div>
                </div>
                <a class="carousel-control-prev " href="#carouselCon" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next " href="#carouselCon" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>  <!-- 메인 화면 사진 -->
          </div>
        </div>
</div>
<div class="container my-1">

    <div class="text-center">
        <h2 class="my-5"><i class="fas fa-home fa-lg"></i> 객실 소개 / 정보</h2>
    </div>

    <div class="container-fluid">
        <div class="card">
          <div class="card-body" style="text-align: center;">
              <img src="{% static 'room/room-map.jpg' %}"
                   style="max-width: 100%; height: auto; display: block; border-radius: 10px;" alt="메인뷰"><br>
              <h3><strong>파라다이스 펜션의 객실을 소개 드립니다.</strong></h3>
<br>
              <p>해당 버튼을 누르면 상세 설명 페이지로 넘어갑니다.</p>
                <a href="{% url 'index:room101' %}"><button type="button" class="btn btn-primary">101호</button></a>
                <a href="{% url 'index:room101' %}"><button type="button" class="btn btn-secondary">102호(독채)</button></a>
                <a href="{% url 'index:room201' %}"><button type="button" class="btn btn-success">201호(월풀)</button></a>
                <a href="{% url 'index:room201' %}"><button type="button" class="btn btn-danger">202호(월풀)</button></a>
                <a href="{% url 'index:room301' %}"><button type="button" class="btn btn-warning">301호(월풀)</button></a>
                <a href="{% url 'index:room301' %}"><button type="button" class="btn btn-info">302호(월풀)</button></a>
                <a href="{% url 'index:room301' %}"><button type="button" class="btn btn-light">303호(월풀)</button></a>
                <a href="{% url 'index:room301' %}"><button type="button" class="btn btn-dark">304호(월풀)</button></a>
          </div>
        </div>
<br>
         <div class="card">
          <div class="card-body" style="text-align: center;">
              <strong>소개된 내용 이외에 필요한 정보가 있다면 전화문의를 주시거나 본 홈페이지의 게시판에 문의 남겨주시면
                  성심성의껏 답변해드리겠습니다.<br>늘 최선을 다하는 파라다이스 펜션이 되겠습니다. 방문해주셔서 감사합니다.</strong>
          </div>
        </div>
<br>
    </div>
</div>


<!-- 위의 내용은 일단은 기본형식으로 하고 아래부터 HTML 코드로 작성하시면 됩니다. -->

{% endblock %}
<!-- 본문내용 끝 -->

{% block script %}
    <script src="https://use.fontawesome.com/releases/v5.2.0/js/all.js"></script>
{% endblock%}