config/urls.py
from index import views
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', include('index.urls')),
    path('', views.index, name='index'),
    path('psbo/', include('psbo.urls')),
    path('common/', include('common.urls')),
]

psbo/urls.py
from django.urls import path
from . import views


app_name = 'psbo'


urlpatterns = [
    path('', views.board, name='board'),
    path('<int:question_id>/', views.detail, name='detail'),


    path('question/create/', views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', views.question_delete, name="question_delete"),


    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', views.answer_delete, name='answer_delete'),
]

psbo/models.py
from django.db import models
from django.contrib.auth.models import User


class Question(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.subject


class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.content

psbo/forms.py
from django import forms

from psbo.models import Question, Answer


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['subject', 'content']
        labels = {
            'subject': '제목',
            'content': '내용',
        }


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content': '답변내용',
        }

psbo/views.py
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from .models import Question, Answer
from django.utils import timezone
from .forms import QuestionForm, AnswerForm
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Q


def board(request):
    # 질문 목록 출력 함수
    # 입력인자
    page = request.GET.get('page', '1')
    kw = request.GET.get('kw', '')

    # 조회
    question_list = Question.objects.order_by('-create_date')

    # 검색
    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |  # 제목검색
            Q(content__icontains=kw) |  # 내용검색
            Q(author__username__icontains=kw) |  # 질문 글쓴이검색
            Q(answer__author__username__icontains=kw)  # 답변 글쓴이검색
        ).distinct()

    # 페이징 처리
    paginator = Paginator(question_list, 12)
    page_obj = paginator.get_page(page)

    context = {'question_list': page_obj}
    return render(request, 'psbo/question_list.html', context)


def detail(request, question_id):
    # 질문 내용 출력 함수
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'psbo/question_detail.html', context)


@login_required(login_url='common:login')
def question_create(request):
    # 글 등록 함수
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.create_date = timezone.now()
            question.save()
            return redirect('psbo:board')
    else:
        form = QuestionForm()
    context = {'form': form}
    return render(request, 'psbo/question_form.html', context)


@login_required(login_url='common:login')
def question_modify(request, question_id):
    # 질문 수정함수
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('psbo:detail', question_id=question.id)

    if request.method == 'POST':
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.modify_date = timezone.now()
            question.save()
            return redirect('psbo:detail', question_id=question.id)

    else:
        form = QuestionForm(instance=question)

    context = {'form':form}
    return render(request, 'psbo/question_form.html', context)


@login_required(login_url='common:login')
def question_delete(request, question_id):
    # 질문 삭제 함수
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '삭제권한이 없습니다.')
        return redirect('psbo:detail', question_id=question.id)
    question.delete()
    return redirect('psbo:board')


@login_required(login_url='common:login')
def answer_create(request, question_id):
    # 답변 등록 함수
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('psbo:detail', question_id=question.id)
    else:
        form = AnswerForm()
    context = {'question': question, 'form': form}
    return render(request, 'psbo/question_detail.html', context)


@login_required(login_url='common:login')
def answer_modify(request, answer_id):
    # 답변 수정 함수
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '수정권한이 없습니다.')
        return redirect('psbo:detail', question_id=answer.question.id)

    if request.method == 'POST':
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.modify_date = timezone.now()
            answer.save()
            return redirect('{}#answer_{}'.format(
                resolve_url('psbo:detail', question_id=answer.question.id), answer.id))
    else:
        form = AnswerForm(instance=answer)
    context = {'answer':answer, 'form':form}
    return render(request, 'psbo/answer_form.html', context)


@login_required(login_url='common:login')
def answer_delete(request, answer_id):
    # 답변 삭제 함수
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '삭제권한이 없습니다.')
    else:
        answer.delete()
    return redirect('psbo:detail', question_id=answer.question.id)

templates/psbo/answer_form.html
{% extends 'base.html' %}

{% block content %}

<div class="container my-3">
    <form method="post" class="post-form">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="content">답변내용</label>
            <textarea class="form-control" name="content" id="content" rows="10">
                {{ form.content.value|default_if_none:'' }}
            </textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>

{% endblock %}

templates/psbo/question_detail.html
{% extends 'base.html' %}

{% block content %}
<br>
<div class="container my-1">
    <table class="table my-1">
        <thead>
            <tr class="thead-dark">
                <th>펜션 자유게시판</th>
            </tr>
        </thead>
    </table>
</div>

<div class="container my-3">
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ question.content }}</div>
            <div class="d-flex justify-content-end">

                <!-- 질문 수정일시 추가 -->
                {% if question.modify_date %}
                <div class="badge badge-light p-2 text-left mx-3">
                  <div class="mb-2">수정시간</div>
                  <div>{{ question.modify_date }}</div>
                </div>
                {% endif %}

                <div class="badge badge-light p-2 text-left">
                    <div class="mb-2">{{ question.author.username }}</div>
                    <div>{{ question.create_date }}</div>
                </div>
            </div>

            <!-- 질문수정, 삭제버튼 -->
            {% if request.user == question.author %}
            <div class="my-3">
              <a href="{% url 'psbo:question_modify' question.id %}"
                 class="btn btn-sm btn-outline-secondary">수정</a>
              <a href="#" class="delete btn btn-sm btn-outline-secondary"
                 data-uri="{% url 'psbo:question_delete' question.id %}">삭제</a>
            </div>
            {% endif %}


        </div>
    </div>


    <h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변이 있습니다.</h5>


    {% for answer in question.answer_set.all %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
            <div class="d-flex justify-content-end">

                <!-- 답변 수정일시 추가 -->
                {% if answer.modify_date %}
                <div class="badge badge-light p-2 text-left mx-3">
                  <div class="mb-2">수정시간</div>
                  <div>{{ answer.modify_date }}</div>
                </div>
                {% endif %}

                <div class="badge badge-light p-2 text-left">
                    <div class="mb-2">{{ answer.author.username }}</div>
                    <div>{{ answer.create_date }}</div>
                </div>
            </div>

            <!-- 답변 수정, 삭제 버튼 추가 -->
            {% if request.user == answer.author %}
            <div class="my-3">
              <a href="{% url 'psbo:answer_modify' answer.id %}"
                   class="btn btn-sm btn-outline-secondary">수정</a>
              <a href="#" class="delete btn btn-sm btn-outline-secondary"
                   data-uri="{% url 'psbo:answer_delete' answer.id %}">삭제</a>
            </div>
            {% endif %}

        </div>
    </div>
    {% endfor %}
    <form action="{% url 'psbo:answer_create' question.id %}" method="post" class="my-3">
        {% csrf_token %}
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
        {% for field in form %}
            {% if field.errors %}
            <strong>{{ field.label }}</strong>
            {{ field.errors }}
            {% endif %}
        {% endfor %}
        </div>
        {% endif %}
        <div class="form-group">
            <textarea name="content" id="content"
                      {% if not user.is_authenticated %}disabled{% endif %}
                      class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>
{% endblock %}


<!--자바스크립트 Start-->
{% block script %}
<script type="text/javascript">
  $(document).ready(function(){

    $(".delete").on('click', function(){
      if(confirm("정말로 삭제하시겠습니까?")){location.href = $(this).data('uri');}
    });

  });
</script>
{% endblock %}
<!--자바스크립트 End-->

templates/psbo/question_form.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문 등록</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
<!--        {{ form.as_p }}-->
<!--        유효성 위배 오류 처리 -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
        {% for field in form %}
            {% if field.errors %}
            <strong>{{ field.label }}</strong>
            {{ field.errors }}
            {% endif %}
        {% endfor %}
        </div>
        {% endif %}
<!--        유효성 위배 오류 처리 끝 -->

        <div class="form-group">
            <label for="subject">제목</label>
            <input type="text" class="form-control" name="subject" id="subject"
                   value="{{ form.subject.value|default_if_none:'' }}">
        </div>

        <div class="form-group">
            <label for="content">내용</label>
            <textarea class="form-control" name="content" id="content"
                      rows="10">{{ form.content.value|default_if_none:''}}</textarea>
        </div>

        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>

{% endblock %}

templates/psbo/question_list.html
{% extends 'base.html' %}
{% load static %}
{% load psbo_filter %}
{% block content %}
<br>
<div class="container my-1">
        <div class="card">
            <div id ="carouselCon" class="carousel slide w-auto mx-auto" data-ride="carousel">
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <img src="{% static 'img_main/1.jpg' %}" class="d-block w-100" alt="...">
                    </div>
                    <div class="carousel-item">
                        <img src="{% static 'img_main/2.jpg' %}" class="d-block w-100" alt="...">
                    </div>
                    <div class="carousel-item">
                        <img src="{% static 'img_main/3.jpg' %}" class="d-block w-100" alt="...">
                    </div>
                    <div class="carousel-item">
                        <img src="{% static 'img_main/4.jpg' %}" class="d-block w-100" alt="...">
                    </div>
                </div>
                <a class="carousel-control-prev " href="#carouselCon" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next " href="#carouselCon" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>  <!-- 메인 화면 사진 -->
          </div>
        </div>
</div>

<div class="container my-1">
    <div class="text-center">
        <h2 class="my-5"><i class="fas fa-clipboard fa-lg"></i> 파라다이스 자유게시판</h2>
    </div>
</div>

<div class="container my-1">
    <div class="row justify-content-end my-1">
        <!-- 검색기능 추가 -->
        <div class="col-4 input-group">
            <input type="text" class="form-control kw" value="{{ kw|default_if_none:'' }}">
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="button" id="btn_search">검색</button>
            </div>
        </div>
        <!-- 검색기능 끝 -->
    </div>
    <table class="table">
        <thead>
        <tr class="thead-dark text-center">
            <th>번호</th>
            <th style="width:50%">제목</th>
            <th>글쓴이</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list %}
        <tr class="text-center">
            <td>
                {{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }}
            </td>
            <td class="text-left">
                <a href="{% url 'psbo:detail' question.id %}" style="color:black">{{ question.subject }}</a>
                {% if question.answer_set.count > 0 %}
                <span class="text-danger small ml-2">[{{ question.answer_set.count }}]</span>
                {% endif %}
            </td>
            <td>{{ question.author.username }}</td>
            <td>{{ question.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>

    <!--    페이징 처리 시작-->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if question_list.has_previous %}
        <li class="page-item">
            <a class="page-link" data-page="{{ question_list.previous_page_number }}" href="#">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}

        <!-- 페이지 리스트 -->
        {% for page_number in question_list.paginator.page_range %}
        {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}
            {% if page_number == question_list.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" data-page="{{ page_number }}" href="#">
                    {{ page_number }}
                </a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" data-page="{{ page_number }}" href="#">
                    {{ page_number }}
                </a>
            </li>
            {% endif %}
        {% endif %}
        {% endfor %}

        <!-- 다음 페이지 -->
        {% if question_list.has_next %}
        <li class="page-item">
            <a class="page-link" data-page="{{ question_list.next_page_number }}" href="#">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징 처리 끝 -->

    <a href="{% url 'psbo:question_create' %}" class="btn btn-primary">게시글 작성</a>
</div>

<form id="searchForm" method="get" action="{% url 'psbo:board' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
</form>

{% endblock %}

{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $(".page-link").on('click', function() {
        $("#page").val($(this).data("page"));
        $("#searchForm").submit();
    });

    $("#btn_search").on('click', function() {
        $("#kw").val($(".kw").val());
        $("#page").val(1);
        $("#searchForm").submit();
    });
});
</script>
<script src="https://use.fontawesome.com/releases/v5.2.0/js/all.js"></script>
{% endblock %}