common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(
        template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup')
]

config/urls.py
from index import views
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', include('index.urls')),
    path('', views.index, name='index'),
    path('psbo/', include('psbo.urls')),
    path('common/', include('common.urls')),
]

index/urls.py
from django.urls import path
from . import views

app_name = 'index'

urlpatterns = [
    path('', views.index, name='index'),
    path('introduce/', views.introduce, name='introduce'),
    path('room/', views.room, name='room'),
    path('travel/', views.travel, name='travel'),
    path('fac/', views.fac, name='fac'),
    path('reservation/', views.reservation, name='reservation'),
    path('location', views.location, name='location'),
    path('reservating/', views.reservating, name='reservating'),
    path('reservating2/', views.reservating2, name='reservating2'),
    path('reserve/', views.reserve, name='reserve'),
    path('charge_info/', views.charge_info, name='charge_info'),

    path('room/101/', views.room101, name='room101'),
    path('room/201/', views.room201, name='room201'),
    path('room/301/', views.room301, name='room301'),


    path('popup/', views.popup, name='popup'),
    path('test/', views.test, name='test'),

]

psbo/urls.py
from django.urls import path
from . import views


app_name = 'psbo'


urlpatterns = [
    path('', views.board, name='board'),
    path('<int:question_id>/', views.detail, name='detail'),


    path('question/create/', views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', views.question_delete, name="question_delete"),


    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', views.answer_delete, name='answer_delete'),
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<!--     부트스트랩 CSS-->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.css' %}">
    <title>Pension Paradise</title>
    <style>
        body{background-color: #f5f5f5; padding-top:50px;}
        {% block style %}
        {% endblock %}
    </style>
</head>
<body>
{% include "navbar2.html" %}

<!--기본 템플릿 안에 삽입될 내용 Start-->
{% block content %}
{% endblock %}
<!--기본 템플릿 안에 삽입될 내용 End-->
<br>
<footer class="py-4 bg-dark nt_footer">
    <div class="container">
        <div class="footer_box">
            <div>
                <p class="footer_text" style="color:#a0a0a0">
                    브랜드명 : <strong>Pension Paradise</strong> ㅣ 대표자 : ㅇㅇㅇ ㅣ 사업자등록번호 : 123-12-12345<br>
                    주소 : 강원도 ㅇㅇ군 ㅇㅇ면 ㅇㅇ리 0000-0 <br>
                    계좌번호 : 농협(홍길동) XXX-02XX-XXXX-XX ㅣ  예약문의 : 010-0000-0000<br>
                </p>
            </div>
           <div style="float:right;">
                <p class="footer_text" style="color:#a0a0a0">
                    Contact Us &nbsp;ㅣ
                    &nbsp;&nbsp;<i class="fas fa-envelope-square"></i>&nbsp;&nbsp;ㅣ
                    &nbsp;&nbsp;<i class="fab fa-twitter-square"></i>&nbsp;&nbsp;ㅣ
                    &nbsp;&nbsp;<i class="fab fa-instagram"></i>&nbsp;&nbsp;ㅣ
                    &nbsp;&nbsp;<i class="fab fa-facebook-square"></i>&nbsp;&nbsp;ㅣ
                </p>
            </div>
        </div>
    </div>
    <!-- /.container -->
</footer>

<!-- 제이쿼리 JS -->
<script src="{% static 'jquery-3.6.0.js' %}"></script>
<!-- 부트스트랩 JS -->
<script src="{% static 'bootstrap.bundle.js' %}"></script>
<script src="{% static 'bootstrap.js' %}"></script>
<!--자바스크립트 Start-->
{% block script %}
{% endblock %}
<!--자바스크립트 End-->
</body>
</html>

templates/form_errors.html
{% if form.errors %}
  {% for field in form %} <!-- 필드오류출력 -->
    {% for error in field.errors %}
      <div class="alert alert-danger">
        <strong>{{ field.label }}</strong>
        {{ error }}
      </div>
    {% endfor %}
  {% endfor %}
  {% for error in form.non_field_errors %} <!-- 논필드 오류출력 -->
    <div class="alert alert-danger">
        <strong>{{ error }}</strong>
    </div>
  {% endfor %}
{% endif %}

templates/navbar.html
{% load static %}
<div class="navigation">

    <!--네비게이션 바-->
    <nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light border-bottom">

        <!-- 왼쪽 부분 -->
        <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2" id="navbarNav">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item" style="padding-left:50px;">
                    <a class="nav-link" href="{% url 'index:introduce' %}"><strong>펜션소개</strong></a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'index:room' %}"><strong>객실정보</strong></a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'index:travel' %}"><strong>여행지정보</strong></a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'index:fac' %}"><strong>주변편의시설</strong></a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'psbo:board' %}"><strong>자유게시판</strong></a>
                </li>

            </ul>
        </div>
        <!-- 왼쪽 부분 끝 -->

        <!--로고 부분-->
        <div>
        <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <a class="navbar" href="{% url 'index:index' %}">
            <img src="{% static 'pension_logo.jpg' %}" width="120px" height="50px" alt="로고"
            style="border: 2px solid black; border-radius: 10px; "></a>

        <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav-R"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        </div>
        <!--로고 부분-->

        <!-- 오른쪽 부분 -->
        <div class="navbar-collapse collapse w-100 order-3 dual-collapse2" id="navbarNav-R">
            <ul class="navbar-nav ml-auto">

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'index:reservation' %}"><strong>예약안내</strong></a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'index:reservating2' %}"><strong>실시간예약</strong></a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'index:location' %}"><strong>오시는길</strong></a>
                </li>

                <li class="nav-item">
                    {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:logout' %}">
                        <strong>'{{ user.username }}'님(로그아웃)</strong></a>
                    {% else %}
                    <a class="nav-link" href="{% url 'common:login' %}"><strong>로그인</strong></a>
                    {% endif %}
                </li>

                <li class="nav-item" style="padding-right:50px;">
                    <a class="nav-link" href="{% url 'common:signup' %}"><strong>회원가입</strong></a>
                </li>

            </ul>
        </div>
        <!-- 오른쪽 부분 끝 -->

    </nav>

</div>

templates/navbar2.html
{% load static %}

<nav class="navbar fixed-top navbar-expand-sm bg-dark navbar-dark">
    <!-- 제목 -->
    <a class="navbar-brand" href="{% url 'index:index' %}"><strong>Paradise</strong></a>

    <!-- Toggler/collapsibe Button -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar"
              aria-controls="collapsibleNavbar" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <!-- 리스트 : 부트스트랩은 모바일 우선이라 화면이 작으면 아래로 쌓아서 내려온다 -->
        <ul class="navbar-nav navbar-dark">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'index:introduce' %}">
                    <i class="fas fa-info-circle"></i>&nbsp;<strong>펜션소개</strong></a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{% url 'index:room' %}">
                    <i class="fas fa-home"></i>&nbsp;<strong>객실정보</strong></a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{% url 'index:travel' %}">
                    <i class="fas fa-map-pin"></i>&nbsp;<strong>여행지정보</strong></a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{% url 'index:fac' %}">
                    <i class="fas fa-map-pin"></i>&nbsp;<strong>주변편의시설</strong></a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{% url 'psbo:board' %}">
                    <i class="fas fa-clipboard"></i>&nbsp;<strong>자유게시판</strong></a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{% url 'index:reservation' %}">
                    <i class="fas fa-calendar-alt"></i>&nbsp;<strong>예약정보</strong></a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{% url 'index:reservating2' %}">
                    <i class="fas fa-calendar-alt"></i>&nbsp;<strong>실시간예약</strong></a>
           </li>

            <li class="nav-item">
                <a class="nav-link" href="{% url 'index:location' %}">
                    <i class="fas fa-bus"></i>&nbsp;<strong>오시는길</strong></a>
            </li>

        </ul>

        <!-- Search -->
        <form class="form-inline ml-auto" action="">
            <!-- inline여야 간격이 없이 메뉴처럼 나온다. ml-atuo : 우측으로 붙게하기-->
            <ul class="navbar-nav navbar-dark">
                <li class="nav-item">
                    {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:logout' %}">
                        <i class="fas fa-sign-out-alt"></i>&nbsp;'{{ user.username }}'님(로그아웃)</a>
                    {% else %}
                    <a class="nav-link" href="{% url 'common:login' %}">
                        <i class="fas fa-sign-in-alt"></i>&nbsp;로그인</a>
                    {% endif %}
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'common:signup' %}">
                        <i class="fas fa-sign-in-alt"></i>&nbsp;회원가입</a>
                </li>
            </ul>
        </form>
    </div>
</nav>


<script src="https://use.fontawesome.com/releases/v5.2.0/js/all.js"></script>